name: Debug Firebase Envs RAW

on:
  push:
    branches:
      - main

jobs:
  debug-env:
    runs-on: ubuntu-latest

    steps:
      - name: Print Firebase env values
        env:
          FIREBASE_APIKEY: ${{ secrets.FIREBASE_APIKEY }}
          FIREBASE_APPID: ${{ secrets.FIREBASE_APPID }}
          FIREBASE_AUTHDOMAIN: ${{ secrets.FIREBASE_AUTHDOMAIN }}
          FIREBASE_DATABASEURL: ${{ secrets.FIREBASE_DATABASEURL }}
          FIREBASE_MESSAGINGSENDERID: ${{ secrets.FIREBASE_MESSAGINGSENDERID }}
          FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
          FIREBASE_STORAGEBUCKET: ${{ secrets.FIREBASE_STORAGEBUCKET }}
          FIREBASE_MEASUREMENTID: ${{ secrets.FIREBASE_MEASUREMENTID }}
        run: |
          echo "FIREBASE_APIKEY=$FIREBASE_APIKEY"
          echo "FIREBASE_APPID=$FIREBASE_APPID"
          echo "FIREBASE_AUTHDOMAIN=$FIREBASE_AUTHDOMAIN"
          echo "FIREBASE_DATABASEURL=$FIREBASE_DATABASEURL"
          echo "FIREBASE_MESSAGINGSENDERID=$FIREBASE_MESSAGINGSENDERID"
          echo "FIREBASE_PROJECTID=$FIREBASE_PROJECTID"
          echo "FIREBASE_STORAGEBUCKET=$FIREBASE_STORAGEBUCKET"
          echo "FIREBASE_MEASUREMENTID=$FIREBASE_MEASUREMENTID"
